from app.api.routes.authentication import auth_router
from app.api.routes.breeding_routes import breeding_router
from app.api.routes.dog_routes import dog_router
from app.api.routes.image_routes import media_router
from app.api.routes.litter_routes import litter_router
from app.api.routes.navigation_routes import navigation_router
from app.api.routes.page_routes import page_router
from app.api.routes.production_routes import production_router
from app.api.routes.search_routes import search_router
from app.api.routes.user_routes import user_router
from app.api.routes.utils import utils_router
from app.api.routes.website_settings_routes import settings_router
from app.api.routes.service_routes import service_router
from app.api.routes.waitlist_routes import waitlist_router
from app.api.routes.contact_routes import contact_router
from app.api.routes.admin_routes import admin_router
from app.api.routes.announcement_routes import announcement_router
