trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: ttnf

stages:
  - stage: BuildAndDeployBackendDev
    jobs:
      - job: BuildBackend
        steps:
          - checkout: self

          - task: Docker@2
            inputs:
              containerRegistry: 'ttnfdockerservice'
              repository: 'backend-dev'  
              command: 'buildAndPush'
              Dockerfile: 'backend/Dockerfile'
              tags: |
                $(Build.BuildId)-dev

          - task: AzureWebAppContainer@1
            inputs:
              azureSubscription: 'ttnfconnect' 
              appName: 'ttnf-api-dev'  
              containers: 'ttnfregistry.azurecr.io/backend-dev:$(Build.BuildId)-dev'

  - stage: BuildAndDeployFrontendDev
    jobs:
      - job: BuildFrontend
        steps:
          - checkout: self
          - script: echo $(REACT_APP_BACKEND_URL)
            displayName: 'Verify REACT_APP_BACKEND_URL is set'

          - task: Docker@2
            inputs:
              containerRegistry: 'ttnfdockerservice'
              repository: 'frontend-dev' 
              command: 'buildAndPush'
              Dockerfile: 'frontend/Dockerfile'
              buildArguments: |
                REACT_APP_BACKEND_URL=$(REACT_APP_BACKEND_URL)
                REACT_APP_TINYMCE_API_KEY=$(REACT_APP_TINYMCE_API_KEY)
                REACT_APP_ENV=dev
              tags: |
                $(Build.BuildId)-dev

          - task: AzureWebAppContainer@1
            inputs:
              azureSubscription: 'ttnfconnect'  
              appName: 'ttnf-dev'  
              containers: 'ttnfregistry.azurecr.io/frontend-dev:$(Build.BuildId)-dev'

  - stage: ApprovalGate
    dependsOn:
      - BuildAndDeployBackendDev
      - BuildAndDeployFrontendDev
    jobs:
      - job: Approval
        pool: server
        steps:
          - task: ManualValidation@0
            inputs:
              instructions: 'Approve to promote to production'

  - stage: PromoteToProduction
    dependsOn: ApprovalGate
    jobs:
      - deployment: DeployBackendProd
        environment: 'Production'
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self

                - task: Docker@2
                  displayName: 'Tag Backend Image for Production'
                  inputs:
                    containerRegistry: 'ttnfdockerservice'
                    repository: 'backend-dev'
                    command: 'tag'
                    imageName: 'ttnfregistry.azurecr.io/backend-dev:$(Build.BuildId)-dev'  # Source image
                    targetImageName: 'ttnfregistry.azurecr.io/backend:prod'                # Target image

                - task: Docker@2
                  displayName: 'Push Backend Image to Production'
                  inputs:
                    containerRegistry: 'ttnfdockerservice'
                    repository: 'backend'
                    command: 'push'
                    imageName: 'ttnfregistry.azurecr.io/backend:prod'

                - task: AzureWebAppContainer@1
                  inputs:
                    azureSubscription: 'ttnfconnect'
                    appName: 'ttnfapi'
                    containers: 'ttnfregistry.azurecr.io/backend:prod'

      - deployment: DeployFrontendProd
        environment: 'Production'
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self

                - task: Docker@2
                  displayName: 'Tag Frontend Image for Production'
                  inputs:
                    containerRegistry: 'ttnfdockerservice'
                    repository: 'frontend-dev'
                    command: 'tag'
                    imageName: 'ttnfregistry.azurecr.io/frontend-dev:$(Build.BuildId)-dev'  # Source image
                    targetImageName: 'ttnfregistry.azurecr.io/frontend:prod'                 # Target image

                - task: Docker@2
                  displayName: 'Push Frontend Image to Production'
                  inputs:
                    containerRegistry: 'ttnfdockerservice'
                    repository: 'frontend'
                    command: 'push'
                    imageName: 'ttnfregistry.azurecr.io/frontend:prod'

                - task: AzureWebAppContainer@1
                  inputs:
                    azureSubscription: 'ttnfconnect'
                    appName: 'ttnfpub'
                    containers: 'ttnfregistry.azurecr.io/frontend:prod'