trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: BuildAndDeployBackend
    jobs:
      - job: BuildBackend
        steps:
          - checkout: self
          
          - task: Docker@2
            inputs:
              containerRegistry: 'ttnfdockerservice'
              repository: 'backend'  
              command: 'buildAndPush'
              Dockerfile: 'backend/Dockerfile'
              tags: |
                $(Build.BuildId)

          - task: AzureWebAppContainer@1
            inputs:
              azureSubscription: 'ttnfconnect'  
              appName: 'ttnfapi'
              containers: |
                container: 'ttnfregistry.azurecr.io/backend:$(Build.BuildId)'  # Point to your backend image in ACR

  - stage: BuildAndDeployFrontend
    jobs:
      - job: BuildFrontend
        steps:
          - checkout: self

          - task: Docker@2
            inputs:
              containerRegistry: 'ttnfdockerservice'
              repository: 'frontend' 
              command: 'buildAndPush'
              Dockerfile: 'frontend/Dockerfile'
              tags: |
                $(Build.BuildId)

          - task: AzureWebAppContainer@1
            inputs:
              azureSubscription: 'ttnfconnect'  
              appName: 'ttnfpub'
              containers: |
                container: 'ttnfregistry.azurecr.io/frontend:$(Build.BuildId)'  # Point to your frontend image in ACR