trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: BuildAndDeployBackend
    displayName: "Build and Deploy Backend"
    jobs:
      - job: BuildBackend
        displayName: "Build and Deploy Python Backend"
        steps:
          - checkout: self

          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.x'
              addToPath: true

          - script: |
              cd ./backend
              python -m venv venv
              source venv/bin/activate
              pip install -r requirements.txt
            displayName: 'Install Backend Dependencies'

          - task: ArchiveFiles@2
            inputs:
              rootFolderOrFile: 'backend'
              includeRootFolder: false
              archiveType: 'zip'
              archiveFile: '$(Build.ArtifactStagingDirectory)/backend.zip'
              replaceExistingArchive: true
            displayName: 'Create Backend Package'

          - script: |
              unzip -l $(Build.ArtifactStagingDirectory)/backend.zip
            displayName: 'List Backend ZIP Contents'
            
          - task: AzureWebApp@1
            inputs:
              azureSubscription: '5b65b6b5-9787-40a8-b3d4-912c139cd62f'
              appName: 'ttnf-backend'
              package: '$(Build.ArtifactStagingDirectory)/backend.zip'
              appSettings: '-WEBSITES_PORT 8000'
            displayName: 'Deploy Backend to Azure App Service'
  - stage: BuildAndDeployFrontend
    displayName: "Build and Deploy Frontend"
    jobs:
      - job: BuildFrontend
        displayName: "Build and Deploy React Frontend"
        steps:
          - checkout: self

          - task: NodeTool@0
            inputs:
              versionSpec: '16.x'
            displayName: 'Install Node.js'

          - script: |
              cd ./frontend
              npm install
              npm run build
            displayName: 'Install and Build Frontend'

          - task: CopyFiles@2
            inputs:
              SourceFolder: 'frontend/build'
              Contents: '**'
              TargetFolder: '$(Build.ArtifactStagingDirectory)/frontend'
            displayName: 'Copy Frontend Build to Artifact Staging'

          - task: ArchiveFiles@2
            inputs:
              rootFolderOrFile: '$(Build.ArtifactStagingDirectory)/frontend'
              includeRootFolder: false
              archiveType: 'zip'
              archiveFile: '$(Build.ArtifactStagingDirectory)/frontend.zip'
              replaceExistingArchive: true
            displayName: 'Create Frontend Package'

          - task: AzureWebApp@1
            inputs:
              azureSubscription: '5b65b6b5-9787-40a8-b3d4-912c139cd62f'
              appName: 'ttnf-frontend'
              package: '$(Build.ArtifactStagingDirectory)/frontend.zip'
            displayName: 'Deploy Frontend to Azure App Service'