trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: ttnf

stages:
  - stage: BuildAndDeployBackend
    jobs:
      - job: BuildBackend
        steps:
          - checkout: self

          - task: Docker@2
            inputs:
              containerRegistry: 'ttnfdockerservice'
              repository: 'backend'  
              command: 'buildAndPush'
              Dockerfile: 'backend/Dockerfile'
              tags: |
                $(Build.BuildId)

          - task: AzureWebAppContainer@1
            inputs:
              azureSubscription: 'ttnfconnect' 
              appName: 'ttnf-api-dev'  
              containers: 'ttnfregistry.azurecr.io/backend-dev:$(Build.BuildId)'  

  - stage: BuildAndDeployFrontend
    jobs:
      - job: BuildFrontend
        steps:
          - checkout: self
          - script: echo $(REACT_APP_BACKEND_URL)
            displayName: 'Verify REACT_APP_BACKEND_URL is set'

          - task: Docker@2
            inputs:
              containerRegistry: 'ttnfdockerservice'
              repository: 'frontend' 
              command: 'buildAndPush'
              Dockerfile: 'frontend/Dockerfile'
              buildArguments: |
                REACT_APP_BACKEND_URL=$(REACT_APP_BACKEND_URL)
                REACT_APP_TINYMCE_API_KEY=$(REACT_APP_TINYMCE_API_KEY)
                REACT_APP_ENV=prod
              tags: |
                $(Build.BuildId)

          - task: AzureWebAppContainer@1
            inputs:
              azureSubscription: 'ttnfconnect'  
              appName: 'ttnf-dev'  
              containers: 'ttnfregistry.azurecr.io/frontend-dev:$(Build.BuildId)'  