services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
      - ./certs:/app/certs
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    environment:
      - ENVIRONMENT=development
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - ./certs:/app/certs
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - HTTPS=true
      - SSL_CRT_FILE=./certs/localhost.pem
      - SSL_KEY_FILE=./certs/localhost-key.pem
    networks:
      - app-network

  alembic:
    build:
      context: ./backend
    command: alembic upgrade head
    networks:
      - app-network

networks:
  app-network:
    driver: bridge