version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:80"  
    environment:
      - PORT=80
    networks:
      - app-network
    depends_on:
      - frontend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        REACT_APP_BACKEND_URL: http://backend:8000  
    ports:
      - "3000:80" 
    networks:
      - app-network

networks:
  app-network:
    driver: bridge