import logging
import re
import asyncio
from io import BytesIO
from fastapi import UploadFile
from sqlalchemy.ext.asyncio import AsyncSession, create_async_engine
from sqlalchemy.orm import sessionmaker
from sqlalchemy.exc import SQLAlchemyError
from sqlalchemy.future import select
from app.core.database import Base
from app.models import Dog, Production, Photo
from app.core.config import settings
from app.services.image_service import MediaService  # Import MediaService

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

DATABASE_URL = settings.sqlalchemy_database_url.replace(
    "postgresql://", "postgresql+asyncpg://"
)


def create_async_session(database_url: str):
    try:
        engine = create_async_engine(database_url, echo=True)
        async_session = sessionmaker(
            bind=engine, class_=AsyncSession, expire_on_commit=False
        )
        logger.info("Database connected and async session created.")
        return async_session
    except SQLAlchemyError as e:
        logger.error("Error connecting to the database: %s", e)
        raise


async def map_files_to_entries(blob_urls, session: AsyncSession):
    try:
        for url in blob_urls:
            # Updated regex to handle more complex URL patterns
            match = re.match(
                r"https://ttnfstore\.blob\.core\.windows\.net/ttnf/(dogs|productions|planned-breedings|home|available)/([^/]+)(?:/.*)?",
                url,
            )
            if not match:
                print(f"URL does not match the expected pattern: {url}")
                continue

            entry_type = match.group(1)
            entry_name = match.group(2).replace("-", " ")  # Normalize the name

            # Simulate file upload by creating a placeholder UploadFile
            image_filename = url.split("/")[-1]
            content = BytesIO(b"")  # Empty file content for simulation
            file = UploadFile(filename=image_filename, file=content)

            # Upload image to the new container
            media_url, _ = await MediaService.upload_media(file, entry_type)

            if entry_type == "dogs":
                # Fetch the corresponding Dog entry
                result = await session.execute(
                    select(Dog).filter(Dog.name.ilike(entry_name))
                )
                dog = result.scalars().first()
                if dog:
                    # Create a new Photo entry with the uploaded media URL
                    photo = Photo(dog_id=dog.id, photo_url=media_url, alt=dog.name)
                    session.add(photo)
                    print(f"Added photo for Dog: {dog.name}")
                else:
                    print(f"No Dog entry found for name: {entry_name}")

            elif entry_type == "productions":
                # Fetch the corresponding Production entry
                result = await session.execute(
                    select(Production).filter(Production.name.ilike(entry_name))
                )
                production = result.scalars().first()
                if production:
                    # Update the profile_photo for the Production entry
                    production.profile_photo = media_url
                    print(f"Set profile photo for Production: {production.name}")
                else:
                    print(f"No Production entry found for name: {entry_name}")

        # Commit the session to save changes
        await session.commit()
    except Exception as e:
        print(f"An error occurred: {e}")
        await session.rollback()
    finally:
        await session.close()


async def main():
    async_session = create_async_session(DATABASE_URL)
    async with async_session() as session:
        await map_files_to_entries(blob_urls, session)


# Example usage
blob_urls = [
"https://ttnfstore.blob.core.windows.net/ttnf//037.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf//023.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf//026.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf//027.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf//028.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/home/Untitled-design-1.png",
"https://ttnfstore.blob.core.windows.net/ttnf/home/attachment/029.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/home/attachment/049.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/home/attachment/050.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/home/attachment/015.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/home/attachment/036.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/home/attachment/032.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf//CollageMaker_20220901_011123204-scaled.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf//20220913_135611.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/planned-breedings/CollageMaker_20220901_011123204-1-scaled.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf//YJIGdZU.png",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/yanmar/IMG_3622.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/yanmar/9udMURi.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/yanmar/17cpw75.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/yanmar/1872EE65-E6EE-42DD-9C7B-48F93A3945FA.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/yanmar/AV0DWAi.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/yanmar/IMG_3622-1.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/yanmar/maau4LI.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/yanmar/mResvb0.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/yanmar/oFgeH36.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/yanmar/VuHEJsD-scaled.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/yanmar/xKMpDhJ.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/yanmar/Yanmar.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/yanmar/Yanmar-1.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/yanmar/Yanmar1.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/yanmar/zoMfBkr.png",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/party-monster/IMG_3407.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/party-monster/IMG_3407-1.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/party-monster/pamo-1gHAGEc.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/party-monster/pamo-6Gdq8Hh.png",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/party-monster/pamo-efDbe2l-scaled.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/party-monster/pamo-IQ0uWLf.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/party-monster/pamo-jY5sXlt-scaled.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/party-monster/pamo-lts1YRw.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/party-monster/pamo-pSfkCUf.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/party-monster/pamo-pWyvGzH.png",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/party-monster/pamo-qUaDZfA.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/party-monster/pamo-rqQEeyW.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/party-monster/partymonster3.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/party-monster/partymonster4.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/odyn/odyn9.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/odyn/IMG_3597-scaled.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/odyn/odyn-2Mx9YN1.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/odyn/odyn-6hTM54d.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/odyn/odyn-6QjgkwJ.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/odyn/odyn-632ywf4.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/odyn/odyn-ardDVhl.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/odyn/odyn-aVZx7FR.png",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/odyn/odyn-jV2oCqr.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/odyn/odyn-n3I4ZB0.png",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/odyn/odyn-pGXS9gl.png",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/odyn/odyn-qlfomHJ.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/odyn/odyn-S7O0T2M.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/odyn/odyn-Sf9nkgW.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/odyn/odyn-ySlXm4r.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/odyn/odyn.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/odyn/Odyn-1.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/odyn/odyn1.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/odyn/odyn2.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/odyn/odyn3.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/odyn/odyn4.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/odyn/odyn9-1.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/thunder-cat/IMG_3351-scaled.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/thunder-cat/049.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/thunder-cat/attachment/138.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/thunder-cat/IMG_3317.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/thunder-cat/IMG_3351-1-scaled.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/thunder-cat/thunder-2gVFrXh.png",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/thunder-cat/thunder-jnYHREb.png",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/thunder-cat/thunder-kbqI81V.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/thunder-cat/thunder-nQD6Bp9.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/thunder-cat/thunder-nzvIa1W.png",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/thunder-cat/thunder-OW85yyK.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/thunder-cat/thunder-wxQUYEs.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/thunder-cat/ThunderCat.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/thunder-cat/thundercat1.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/thunder-cat/thundercat2.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/thunder-cat/thundercat3.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/kofi/Kofi.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/kofi/attachment/067.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/kofi/kofi-5RdHpgD.png",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/kofi/kofi-bYuTJ13.png",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/kofi/kofi-FRoEoyF.png",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/kofi/kofi-hoS5qDe.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/kofi/kofi-pAj2eJV.png",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/kofi/kofi-pNrxkbl.png",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/kofi/kofi-TR7vF3L.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/kofi/kofi-tSLhpAm.png",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/kofi/kofi-wbRUXwO.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/kofi/kofi-ybhKWg0.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/kofi/kofi-ZHvn9xw.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/kofi/Kofi-1.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/kofi/kofi1.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/kofi/kofi2.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/izzo/izzo.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/izzo/attachment/087.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/izzo/attachment/139.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/izzo/IMG_20130528_202734.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/izzo/IMG_20150228_141114.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/izzo/izzo-1.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/izzo/IZZO1.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/ecko/attachment/312.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/cartel/Cartel.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/cartel/cartel-download1.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/cartel/Cartel-1.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/cartel/cartel1.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/cartel/cartel2.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/cartel/cartel3.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/cartel/cartel4.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/cartel/cartel6.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/malakai/attachment/093.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/malakai/attachment/009.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/malakai/028.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/malakai/037.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/malakai/attachment/038.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/malakai/093-1.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/malakai/attachment/171.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/malakai/malakai-download.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/malakai/malakai-download2.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/malakai/malakai1.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/malakai/malakai2.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/malakai/malakai3.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/malakai/malakai5.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/malakai/malakai6.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/malakai/malakai7.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/malakai/malakai8.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/malakai/malakai9.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/paper-trail/paper17.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/paper-trail/attachment/255.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/paper-trail/attachment/348.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/paper-trail/paper17-1.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/the-bread-winner/bread1.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/the-bread-winner/attachment/089.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/the-bread-winner/attachment/268.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/the-bread-winner/attachment/357.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/the-bread-winner/attachment/366.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/the-bread-winner/bread1-1.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/beef/IMG_3394.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/beef/attachment/054.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/beef/attachment/288.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/beef/attachment/322.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/beef/IMG_3394-1.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/beef/IMG_3397.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/beef/IMG_3399.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/beef/IMG_3481.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/beef/IMG_3613.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/cash-money/image000007.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/yenko/150-1.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/yenko/026.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/yenko/attachment/122.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/yenko/150-1-1.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/kaz/attachment/326.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/kaz/326-1.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/kaz/attachment/328.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/kaz/kaz1.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/kaz/kaz2.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/kaz/kaz3.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/kaz/kaz4.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/kaz/kaz5.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/kaz/kaz6.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/kaz/kaz7.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/kaz/kaz8.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/kaz/kaz10.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/kaz/kaz11.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/kaz/kaz12.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/kaz/kaz13.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/kaz/production15.png",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/kaz/production29.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/peavy/peavy12.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/peavy/peavy.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/peavy/peavy1.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/peavy/peavy2.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/peavy/peavy3.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/peavy/peavy4.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/peavy/peavy5.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/peavy/peavy6.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/peavy/peavy7.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/peavy/peavy8.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/peavy/peavy9.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/peavy/peavy10.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/peavy/peavy11.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/peavy/peavy12-1.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/peavy/peavy13.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/kayda/production12.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/kayda/attachment/061.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/kayda/attachment/132.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/kayda/IMG_3518-scaled.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/kayda/IMG_3573-scaled.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/kayda/kayda.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/kayda/kayda1.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/kayda/kayda2-1.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/kayda/kayda2.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/kayda/kayda3.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/kayda/kayda4.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/kayda/kayda5.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/kayda/kayda6.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/kayda/kayda7.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/kayda/kayda8.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/kayda/kayda9.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/kayda/production11.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/kayda/production12-1.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/rudolph/20221106_194410.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/rudolph/20221106_194410-1.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/rudolph/rudolph.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/rudolph/rudolph1.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/rudolph/rudolph2-1.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/rudolph/rudolph2.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/rudolph/rudolph3.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/rudolph/rudolph4.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/rudolph/rudolph5.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/rudolph/rudolph6.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/yuki/IMG_3411.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/yuki/029.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/yuki/attachment/059.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/yuki/IMG_3411-1.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/yuki/yazzy1.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/yuki/yazzy2.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/yuki/yuki1.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/yuki/yuki2-1.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/yuki/yuki2.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/yuki/yuki5.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/yuki/yuki6.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/yuki/yuki7.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/yuki/yuki8.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/yuki/yuki9.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/yuki/yuki10.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/yuki/yuki11.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/yakka/IMG_3498.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/yakka/026-1.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/yakka/attachment/129.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/yakka/attachment/183.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/yakka/IMG_3498-1.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/yakka/yakka.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/yakka/yakka1.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/yakka/yakka2-1.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/yakka/yakka2.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/yakka/yakka3.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/tonga/tonga2.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/tonga/tonga-1.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/tonga/tonga.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/tonga/tonga2-1.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/tonga/tonga3.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/tonga/tonga4.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/tonga/tonga5.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/astra/023.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/astra/036.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/astra/attachment/195.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/astra/20221106_191920.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/astra/20221106_191958.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/astra/astra.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/astra/astra1.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/astra/astra2-1.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/astra/astra2.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/astra/astra3.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/astra/astra5.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/astra/astra7.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/astra/astra8.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/astra/production9.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/dirty-money/attachment/116.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/vida/032.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/vida/IMG_3325-scaled.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/vida/IMG_3419.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/vida/IMG_3608.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/yuli/027.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/yuli/attachment/039.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/yuli/attachment/069.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/yuli/attachment/101.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/yuli/attachment/103.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/yuli/attachment/104.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/yuli/IMG_2653.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/yuli/IMG_2770.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/toka/IMG_2789.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/toka/toka3.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/nika/NIKA1.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/nola/attachment/084.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/nola/attachment/157.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/nola/attachment/222.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/nola/attachment/2277.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/toki/015.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/toki/027-1.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/toki/attachment/034.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/toki/attachment/165.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/toki/toki2.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/toki/toki3.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/trilogy/trilogy2.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/taja/production26.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/breedings/narco-x-peavy/download-scaled.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/about-the-frenchie/image.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/about-the-frenchie/image.png",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/aries/aries.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/stella/stella.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/beau-louie/Xgx67pg.png",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/beau-louie/YJIGdZU-e1670618499432.png",
"https://ttnfstore.blob.core.windows.net/ttnf/home/G0yapF7.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/home/G0yapF7-1.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf//YJIGdZU-1.png",
"https://ttnfstore.blob.core.windows.net/ttnf//liam.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf//ricky-baker.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf//oliver.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf//duffee.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/liam/liam-1.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/ricky-baker/ricky-baker-1.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/oliver/oliver-1.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/duffy/duffee-1.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/kofi/kofi.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/kalina/kalina-e1712892576328.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/seven/seven.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/donut/donut.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/chevy/chevy-e1712891737361.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/drake/drake.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/crockett/crockett-e1712892495587.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/henry/henry.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/mr-gus/gus-e1712891546481.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/louie/louie.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/phyllis-sinatra-gambino/phyliss.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/ladybug/ladybug.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/astra/astra.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf//nixi.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/ghost-ryder/ghost-rider-e1712891385972.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/theodore/theodore.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/diesel/diesel.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf//mia.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/luna/luna.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/blue/blue.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/coco-2/coco.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf//kaz.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/lenni-lou/lennie-lou.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/taja/taja.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/lex-luther/lex-luther.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/kiwi/kiwi.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/maxx/max.png",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/skipper/skipper.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/miss-fia/miss-fia.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/beau-louie/321125488_449959877344054_5238302612400792525_n.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/pyper-rose/320725632_480007080921435_4813727481997858277_n.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/priscilla/priscilla.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/home/320277169_920956245566116_7512405805898762110_n-e1672265908918.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/home/G0yapF7-1-1-e1672266707517.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/bucee/321065746_496008432620776_5167445284308649468_n.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/taz/319719896_1332773640859147_2711974200206006097_n.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/cash-money/320532681_8854288564588754_5040864790697386630_n.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/tito-and-blaze/320673452_643562310830840_8575212893564166994_n.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/sassy-kaz/320838029_913910196265404_5787663995364399620_n.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/princess-zelda-and-link/322368847_843344766776387_6864419373881527354_n.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/kb/320512292_1473727086451989_7761702554420139796_n-e1712892085312.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/sariya/320785485_970342687257933_2608109952351664243_n.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/nixi/321584436_4212818425508884_5629351479619592445_n.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/archie/321238333_1090144671655609_8972072037043063940_n.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/nacho/321547543_882879146468335_8033042244382536117_n.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/yenko/312875742_522733856526371_4979629198425035519_n.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/trilogy/321039929_730916408311399_2176271158431773988_n-e1712890639102.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/maverick/322033339_941019917310258_6417652171640222308_n.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/dirty-money/322157838_983882819666988_7557432193029401292_n.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/jett/321241813_724571395761648_533889674935729052_n.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/hippo/322412507_822789385482763_9190988332662906450_n.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/rocky/321412336_5815715448523463_4363941821320453174_n.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/franklin/320933184_563473532317557_7953962819661646456_n-e1712891076347.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/hunter/322509704_448725750644888_8507755398535051440_n.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/mila/322727106_620586843401127_7920537362025844886_n-e1712891218885.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/hippo/322598388_459909679675790_4729468334884758802_n-e1712892402152.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/tinkerbell/322406664_3464967900390867_6470570793647966645_n.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/gizmo/321497403_2324488771065234_140106699871566325_n.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/hayzl/321588300_1134692130525568_4295670201657316074_n.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/peavy/322367570_539702081541842_6458900131414708575_n.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/dotti-lucille/322000681_662265512303755_111816062361874193_n-e1712890724258.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/handsome-jack/322373718_530430929135119_9087733965002784447_n.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/kiva/321613866_880398632983113_1617924259952184038_n.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/coco/321307030_887437462388761_6984147149926255318_n.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/lonely-star/322672804_550510236714683_4724983136898470687_n.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/kyah/321930219_685261899810912_5262342118464570189_n-e1712892197835.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/draco/320679155_875018396975326_4492696543522927967_n.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/olive/321291102_6087672807930291_1323920882250336083_n.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/cartel/321380920_829859504761289_8417141378320718756_n-e1712892323114.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/buttons/321800910_565437861718926_8948389343645369731_n.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/yuli/321769495_693939079113975_7625551546316323247_n.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/kayda/321493028_541187298037158_7917954918097001634_n.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/yuki/321418947_704549474520439_5584726999378381040_n.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/stella-2/321282461_478851031101601_507017038685586429_n.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/rocko/320989006_849780859618579_6923275542863964355_n-e1712890548863.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/doc-holliday/321550690_720938859758891_4028855972471748163_n-e1712892802638.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/beau/322134026_1536520910182982_4556544161321842587_n.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/kali/320244200_1008332056649960_8379979610511662235_n.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/covid/320432601_1189063541701500_3432589543216782029_n.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/money-man/321384080_3251527741765379_5647966188854973611_n.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/doc/225714305_421039125983565_3986952111257721617_n-scaled-e1712892250279.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/noah/321860847_1209184493328666_4702633823122990470_n.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/fendi/318844929_482827783966385_8706495796074777404_n.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/lonely-star/322518552_866518767992205_4751204998563451582_n.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/montana/320827790_873863010479649_3870539961339766508_n.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/stitch/322017984_1320746662022343_3260521707854718848_n.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/fiona/322136581_686264033141538_9143814772207053820_n.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf//322475667_718382856478200_651015187140076560_n.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf//321921227_1259331964620529_2062271736528125201_n.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/lex-luther/322068568_6073801869318371_3552850007424810820_n.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/xo/322097025_1326488101497119_3621122591900720914_n.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/yazzy/321651374_1675878889498803_725193204273055643_n.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/abigail/322552015_503740175161589_5371086554270110275_n.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/toka/321296317_5840502306015917_6258034135144877157_n.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/lil-grizzly/322000705_569919441184905_6230523754785139830_n.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/finn/322191934_1516563065490790_2628980848444223237_n.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/olive-2/320532673_480122934196323_5374298091933816752_n-e1712890455704.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/available/322475667_718382856478200_651015187140076560_n-1.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/available/322535598_5917162268344551_3575349239111597684_n.mp4",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/nova/322017984_516309240594977_7476530727794682761_n.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/the-bread-winner/321724021_933817181328600_8840690424071565808_n.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/beef/321850973_3439722349629186_8600580363610781867_n-1.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/paper-trail/322548821_556130496417817_1062106101502430922_n-1.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/yenko/FB_IMG_1672544884138-1.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/kayda/CollageMaker_20230101_004232686.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/tonga/tonga7-scaled.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/pita/mygirl7.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/pita/mygirl.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/yuki/20230121_121809-scaled.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf//cream2.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf//creamneon3.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/link/image000000004.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/cash/20210822_222333.png",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/dusty-baker-norman/20230215_212927.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/chevy-joe/IMG_2646.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/aspen/FB_IMG_1676518927493.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/the-breadwinner/bread6.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/mia/20230215_215405.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/aspen/FB_IMG_1676518927493-1.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/aspen/FB_IMG_1676518933834.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/tonga/tonga4.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/astra/20230119_204739.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/toka/toka6.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/toka/toka4.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/toka/toka3.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/toka/toka2.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/toka/toka.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/malakai/malakai3.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/malakai/malakai2.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/malakai/malakai1.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/malakai/malakai1-1.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/available/rainbow.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/available/creamneon3.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/available/rainbow-1.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/available/cream4.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/cash-money/image0000011.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/available/cream5.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/available/lilac1.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/available/neon4.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/available/neon2.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/available/lilac1-1.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/available/IMG_3834.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/cash-money/cash1.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/cash-money/cash12.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/cash-money/cash5.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/yanmar/yan4.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/yanmar/yan3.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/yanmar/yan.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/yenko/attachment/18.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/yenko/attachment/17.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/yenko/attachment/9.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/yenko/attachment/7.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/yenko/attachment/4.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/yenko/20230321_194929.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/yenko/335720455_1824617011227062_3550325297653098609_n-2.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/yenko/335773271_1638525866607713_5328791404310869934_n-1.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/aspen/20230321_195019.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/aspen/20230321_194951.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/aspen/20230321_195036.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/breedings/narco-x-peavy/white_logo_color_background-scaled.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/available/plat11.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/yuki/335501891_190297930388795_1409648663227025891_n-1.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/dirty-money/dirty1.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/blu/redwhiteblue5.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/ice/IMG_03201.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/luna-2/merlegirl5.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/kamikaze/lilmerle12.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/ricky-baker/20230321_205149.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/lila/20230321_205952.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/yuki/335501891_190297930388795_1409648663227025891_n-1-1.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/yuki/333609828_1763092720764197_848691622521364423_n-1.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/priscilla/FB_IMG_1679451180368.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/pita/pita.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/duffy/20230321_212830.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/louie-2/plat4.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/tonga/tonga4.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/kamikaze/lilmerle12-1.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/kamikaze/lilmerle2.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/kamikaze/lilmerle9.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/kamikaze/merle9.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/kamikaze/merle8.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/kamikaze/merle6.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/kamikaze/merle4.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/kamikaze/merle3.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/kamikaze/merle2.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/kamikaze/merle1.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/pita/pita.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/pita/pita1.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/pita/mygirl7-1.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf//Xgx67pg-e1680016681651.png",
"https://ttnfstore.blob.core.windows.net/ttnf//Untitled-design.png",
"https://ttnfstore.blob.core.windows.net/ttnf/available/april1o.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/available/april1g.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/available/april1d.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/available/april1f.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/available/april1s.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/available/april1p-scaled.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/tuna/IMG_9206.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/tater/Screenshot_20230402-172824_Business-Suite.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/chevy-joe/20230403_142637.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/neva/april15ww.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/neva/april15b.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/neva/april15v.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/neva/april15c.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/neva/april15x.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/neva/april15z.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/neva/april15l.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/tonga/april15a.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/thunder-cat/april15h.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/thunder-cat/april15q.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/beef/april15y.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/rueger/20230426_194351.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/cash-money/april27k.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/cash-money/april27j.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/kamikaze/april27p.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/kamikaze/april27t.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/kamikaze/april27q.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/kamikaze/april27o.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/kamikaze/april27i.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/yuli/april27h.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/yuli/april27g.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/yuli/april27f.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/yuli/april27d.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/yuli/april27s.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/yuli/april27a.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/yuli/april27y.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/yuli/april27r.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/yuli/april27w.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/sassy-kaz/IMG_3586.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/pyper/pyper30628.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/pyper/pyper30628-1.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/pyper/pyper20628.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/pyper/pyper10628.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/paper-trail/paper80628.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/paper-trail/paper70628.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/paper-trail/paper60628.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/paper-trail/paper50628.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/paper-trail/paper30628.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/paper-trail/paper10628.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/paper-trail/paper0628.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/the-bread-winner/bred90628.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/the-bread-winner/bread80628.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/the-bread-winner/bread70628.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/the-bread-winner/bread60628.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/the-bread-winner/bread50628.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/the-bread-winner/bread40628.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/the-bread-winner/bread30628.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/the-bread-winner/bread20628.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/the-bread-winner/bread10628.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/the-bread-winner/bread0628.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/yenko/yenko-june21a.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/yenko/yenko-june21p.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/yenko/yenko-june21o.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/yenko/yenko-june21i.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/yenko/yenko-june21u.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/yenko/yenko-june21y.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/yenko/yenko-june21t.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/yenko/yenko-june21-r.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/fendi/Screenshot_20230705-174303_Gallery.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/yuli/Screenshot_20230705-174700_Gallery.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/abigail/Screenshot_20230705-174642_Gallery.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/tito-and-blaze/IMG_5463-e1712890044497.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/rocky/received_596741889266879.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/buttons/received_659564505524200-e1712890841923.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/duffy/Screenshot_20230705-174611_Gallery.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/planned-breedings/kamikze-1-scaled.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/planned-breedings/pita-1-scaled.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/planned-breedings/20230808_210931-scaled.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/planned-breedings/Pita2-1.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/planned-breedings/Screenshot_20230812_001308_Instagram.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/planned-breedings/20230807_1751590.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/planned-breedings/Screenshot_20230816_164324_Samsung-Notes.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/planned-breedings/FB_IMG_1689609639627.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/planned-breedings/FB_IMG_1689609635398.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/available/CollageMaker_20230610_010459398-scaled.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/available/image0000011.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/available/Screenshot_20230705-174611_Gallery.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/aspen/Screenshot_20230727-120443_Gallery.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/aspen/Screenshot_20230727-120454_Gallery.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/aspen/Screenshot_20230727-120506_Gallery.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/aspen/Screenshot_20230812_001308_Instagram.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/aspen/kamikaze3-1-scaled.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/sassy-kaz/IMG_4507.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/duffy/Screenshot_20230705-174428_Gallery.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/duffy/Screenshot_20230705-174428_Gallery-1.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/stella-3/Screenshot_20230705-174319_Gallery.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/mia/IMG_1001.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/recommendations/Untitled-document.pdf",
"https://ttnfstore.blob.core.windows.net/ttnf/recommendations/Untitled-document-1.pdf",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/blu/IMG_1395.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/chevy-joe/chevyjoe.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/ice/ice4.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/kamikaze/kamikze-scaled.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/planned-breedings/CollageMaker_20230914_162800339-scaled.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/planned-breedings/CollageMaker_20230914_162800339-1-scaled.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/planned-breedings/CollageMaker_20230914_162800339-2-scaled.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/planned-breedings/CollageMaker_20230914_162800339-3.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/cash-money/cash5-1.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/planned-breedings/IMG_20231025_121614_314-scaled.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/planned-breedings/IMG_20231025_121614_314-1-scaled.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/planned-breedings/IMG_20231025_121614_314-2-scaled.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/planned-breedings/IMG_20231025_121614_314-3.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/available/IMG_8826.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/available/IMG_8765.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/available/IMG_8761.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/available/IMG_8906.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/available/IMG_8906-1.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/available/IMG_8751.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/available/IMG_8751-1.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/high-roller/20231011_221035.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/frankie/IMG_3026.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/bank-roll/IMG_8202.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/kamikaze/IMG_8516.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/taz/IMG_0035.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/kamikaze/IMG_8618.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/available/IMG_9152.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/available/IMG_9278.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/available/IMG_9185.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/available/IMG_9131.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/louie/IMG_9281.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/louie/IMG_9294.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/louie/IMG_9296.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/louie/IMG_9304.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/louie/IMG_9305.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/louie/IMG_9306.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/louie/IMG_9307.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/louie/IMG_9317.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/available/IMG_9743.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/available/IMG_9709.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/available/IMG_9549.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/high-roller/20231011_221035.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/high-roller/IMG_8327.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/high-roller/IMG_8338.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/high-roller/IMG_8449.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/kayda/IMG_9353.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/vida/IMG_9416.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/neva/april15ww-1.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/neva/april15c-1.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/thunder-cat/IMG_9501.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/thunder-cat/IMG_9501-1.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/lex-luther/20231230_101803.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/drax/image00000016.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/jon-benet/IMG_0220.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/wrenly/IMG_7871.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/frankie/20240116_211238.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/sassy-kaz/20240116_211805.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/priscilla/FB_IMG_1702496768352-e1712890120926.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/the-breadwinner/IMG_9651.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/dirty-money/IMG_9343.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/bunny/IMG_9572.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/bunny/IMG_9578.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/bunny/IMG_9619.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/bunny/IMG_9628.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/bunny/IMG_9631.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/available/IMG_0073.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/available/IMG_0079.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/available/IMG_0109.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/available/IMG_0125.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/available/IMG_0141.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/available/IMG_0167.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/available/IMG_0196.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/available/IMG_0197.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/available/IMG_0200.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/available/IMG_0274.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/available/IMG_0281.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/available/IMG_0285.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/available/IMG_0323.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/available/IMG_0342.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/available/IMG_0019.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/bunny/IMG_0839.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/high-roller/IMG_0633.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/high-roller/IMG_0671.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/high-roller/IMG_0696.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/high-roller/IMG_0697.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/high-roller/IMG_0713.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/high-roller/IMG_0720.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/high-roller/IMG_0736.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/high-roller/IMG_0737.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/high-roller/IMG_0759.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/high-roller/IMG_0760.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/high-roller/IMG_0762.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/high-roller/IMG_0765.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/high-roller/IMG_0766.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/high-roller/IMG_0801.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/high-roller/IMG_0849.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/high-roller/IMG_0863.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/astra/IMG_0801.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/the-bread-winner/IMG_9554.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/dogs/yuki/april1e.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/nova-2/IMG_0409.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/chanel/IMG_0019-1.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf//topnotch-r.zip",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/chump-change/IMG_0412.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/sully/IMG_0285-1.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/pricilla-jelly-bean-jo/IMG_9185.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/chump-change/IMG_4572.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/cocoa-pebbles-and-thor/IMG_1191.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/ransom/IMG_7036.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/mera-jolee/FullSizeR.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/drax/attachment/1259564200461928391.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/princess-zelda-and-link/attachment/14864839161379000481.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/chanel/IMG_3599.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/kiwi/IMG_0722-e1712888098355.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/louis/IMG_7203-e1712889826488.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/winter/Messenger_creation_66333073-6CC3-4BCA-8EBC-634122DA3D82_0.jpeg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/tuffy-lou/Screenshot_20240411_213507_Gallery-e1712889540401.jpg",
"https://ttnfstore.blob.core.windows.net/ttnf/productions/ladybug/Messenger_creation_C230F007-FE1F-4055-9101-5FA7ABA18EFC_0-scaled-e1712891860891.jpeg"
]


if __name__ == "__main__":
    asyncio.run(main())
    logger.info("Images successfully mapped")
