from app.services.breeding_service import BreedingService
from app.services.dog_service import DogService
from app.services.litter_service import LitterService
from app.services.production_service import ProductionService
from app.services.user_service import UserService
from app.services.image_service import MediaService
from app.services.search_service import search_resources
from app.services.page_service import PageService
from app.services.navigation_service import NavigationService
from app.services.services_service import ServicesService
from app.services.waitlist_service import WaitlistService
from app.services.contact_service import ContactService
from app.services.email_service import AzureEmailService
