"""added global updated at

Revision ID: 1800297b99eb
Revises: 22094e69643a
Create Date: 2024-09-17 01:40:01.981930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1800297b99eb'
down_revision: Union[str, None] = '22094e69643a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('WebsiteSettings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('setting_key', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_WebsiteSettings_id'), 'WebsiteSettings', ['id'], unique=False)
    op.create_index(op.f('ix_WebsiteSettings_setting_key'), 'WebsiteSettings', ['setting_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_WebsiteSettings_setting_key'), table_name='WebsiteSettings')
    op.drop_index(op.f('ix_WebsiteSettings_id'), table_name='WebsiteSettings')
    op.drop_table('WebsiteSettings')
    # ### end Alembic commands ###
