"""Add many-to-many relationship for sires and dams

Revision ID: 1a4c1031bef6
Revises: 45953bd494b0
Create Date: 2024-10-20 08:42:04.394197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1a4c1031bef6'
down_revision: Union[str, None] = '45953bd494b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('waitlist_dam_association',
                    sa.Column('waitlist_entry_id', sa.Integer(), nullable=False),
                    sa.Column('dog_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['dog_id'], ['dogs.id'], ),
                    sa.ForeignKeyConstraint(['waitlist_entry_id'], ['waitlist_entries.id'], ),
                    sa.PrimaryKeyConstraint('waitlist_entry_id', 'dog_id')
                    )
    op.create_table('waitlist_sire_association',
                    sa.Column('waitlist_entry_id', sa.Integer(), nullable=False),
                    sa.Column('dog_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['dog_id'], ['dogs.id'], ),
                    sa.ForeignKeyConstraint(['waitlist_entry_id'], ['waitlist_entries.id'], ),
                    sa.PrimaryKeyConstraint('waitlist_entry_id', 'dog_id')
                    )
    op.drop_constraint('waitlist_entries_dam_id_fkey', 'waitlist_entries', type_='foreignkey')
    op.drop_constraint('waitlist_entries_sire_id_fkey', 'waitlist_entries', type_='foreignkey')
    op.drop_column('waitlist_entries', 'sire_id')
    op.drop_column('waitlist_entries', 'dam_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('waitlist_entries', sa.Column('dam_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('waitlist_entries', sa.Column('sire_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('waitlist_entries_sire_id_fkey', 'waitlist_entries', 'dogs', ['sire_id'], ['id'])
    op.create_foreign_key('waitlist_entries_dam_id_fkey', 'waitlist_entries', 'dogs', ['dam_id'], ['id'])

    op.drop_table('waitlist_sire_association')
    op.drop_table('waitlist_dam_association')
    # ### end Alembic commands ###
