"""Add CarouselImage model

Revision ID: 2b879487dcf6
Revises: ae2f6cf9fb81
Create Date: 2024-09-27 16:27:28.984693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b879487dcf6'
down_revision: Union[str, None] = 'ae2f6cf9fb81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carousel_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('src', sa.String(), nullable=False),
    sa.Column('alt', sa.String(), nullable=True),
    sa.Column('page_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_carousel_images_id'), 'carousel_images', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_carousel_images_id'), table_name='carousel_images')
    op.drop_table('carousel_images')
    # ### end Alembic commands ###
