"""initial migration

Revision ID: c02104e6feac
Revises: 
Create Date: 2024-08-22 18:33:23.624845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c02104e6feac'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dogs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('gender', sa.Enum('male', 'female', name='genderenum'), nullable=False),
    sa.Column('color', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('available', 'sold', 'stud', 'retired', name='statusenum'), nullable=True),
    sa.Column('profile_photo', sa.String(length=255), nullable=True),
    sa.Column('stud_fee', sa.Integer(), nullable=True),
    sa.Column('sale_fee', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=2500), nullable=True),
    sa.Column('pedigree_link', sa.String(length=255), nullable=True),
    sa.Column('video_url', sa.String(length=255), nullable=True),
    sa.Column('parent_male_id', sa.Integer(), nullable=True),
    sa.Column('parent_female_id', sa.Integer(), nullable=True),
    sa.Column('is_production', sa.Boolean(), nullable=True),
    sa.Column('kennel_own', sa.Boolean(), nullable=True),
    sa.Column('is_retired', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['parent_female_id'], ['dogs.id'], ),
    sa.ForeignKeyConstraint(['parent_male_id'], ['dogs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dogs_id'), 'dogs', ['id'], unique=False)
    op.create_table('nav_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('editable', sa.Boolean(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['nav_links.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_nav_links_id'), 'nav_links', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('company', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('breedings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('female_dog_id', sa.Integer(), nullable=True),
    sa.Column('male_dog_id', sa.Integer(), nullable=True),
    sa.Column('breeding_date', sa.Date(), nullable=True),
    sa.Column('expected_birth_date', sa.Date(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['female_dog_id'], ['dogs.id'], ),
    sa.ForeignKeyConstraint(['male_dog_id'], ['dogs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_breedings_id'), 'breedings', ['id'], unique=False)
    op.create_table('health_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dog_id', sa.Integer(), nullable=True),
    sa.Column('dna', sa.String(length=255), nullable=True),
    sa.Column('carrier_status', sa.String(length=255), nullable=True),
    sa.Column('extra_info', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['dog_id'], ['dogs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_health_info_id'), 'health_info', ['id'], unique=False)
    op.create_table('pages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('custom_values', sa.JSON(), nullable=True),
    sa.Column('external_data', sa.JSON(), nullable=True),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('invalid_block_types', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('translations', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pages_id'), 'pages', ['id'], unique=False)
    op.create_index(op.f('ix_pages_slug'), 'pages', ['slug'], unique=True)
    op.create_table('photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dog_id', sa.Integer(), nullable=True),
    sa.Column('photo_url', sa.String(length=255), nullable=False),
    sa.Column('alt', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['dog_id'], ['dogs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_photos_id'), 'photos', ['id'], unique=False)
    op.create_table('productions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('owner', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('sire_id', sa.Integer(), nullable=True),
    sa.Column('dam_id', sa.Integer(), nullable=True),
    sa.Column('gender', sa.Enum('male', 'female', name='genderenum'), nullable=False),
    sa.Column('profile_photo', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['dam_id'], ['dogs.id'], ),
    sa.ForeignKeyConstraint(['sire_id'], ['dogs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_productions_id'), 'productions', ['id'], unique=False)
    op.create_table('dog_production_link',
    sa.Column('dog_id', sa.Integer(), nullable=True),
    sa.Column('production_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dog_id'], ['dogs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['production_id'], ['productions.id'], ondelete='CASCADE')
    )
    op.create_table('litters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('breeding_id', sa.Integer(), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('number_of_puppies', sa.Integer(), nullable=True),
    sa.Column('litter_url', sa.String(), nullable=True),
    sa.Column('description', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['breeding_id'], ['breedings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_litters_id'), 'litters', ['id'], unique=False)
    op.create_table('litter_puppies',
    sa.Column('litter_id', sa.Integer(), nullable=True),
    sa.Column('dog_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dog_id'], ['dogs.id'], ),
    sa.ForeignKeyConstraint(['litter_id'], ['litters.id'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('litter_puppies')
    op.drop_index(op.f('ix_litters_id'), table_name='litters')
    op.drop_table('litters')
    op.drop_table('dog_production_link')
    op.drop_index(op.f('ix_productions_id'), table_name='productions')
    op.drop_table('productions')
    op.drop_index(op.f('ix_photos_id'), table_name='photos')
    op.drop_table('photos')
    op.drop_index(op.f('ix_pages_slug'), table_name='pages')
    op.drop_index(op.f('ix_pages_id'), table_name='pages')
    op.drop_table('pages')
    op.drop_index(op.f('ix_health_info_id'), table_name='health_info')
    op.drop_table('health_info')
    op.drop_index(op.f('ix_breedings_id'), table_name='breedings')
    op.drop_table('breedings')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_nav_links_id'), table_name='nav_links')
    op.drop_table('nav_links')
    op.drop_index(op.f('ix_dogs_id'), table_name='dogs')
    op.drop_table('dogs')
    # ### end Alembic commands ###
