"""added manual sire to breeding

Revision ID: d9fca9c50162
Revises: 884f80f347a1
Create Date: 2024-10-31 00:35:28.815531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd9fca9c50162'
down_revision: Union[str, None] = '884f80f347a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('breedings', sa.Column('manual_sire_name', sa.String(length=255), nullable=True))
    op.add_column('breedings', sa.Column('manual_sire_color', sa.String(length=50), nullable=True))
    op.add_column('breedings', sa.Column('manual_sire_image_url', sa.String(length=255), nullable=True))
    op.add_column('breedings', sa.Column('manual_sire_pedigree_link', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('breedings', 'manual_sire_pedigree_link')
    op.drop_column('breedings', 'manual_sire_image_url')
    op.drop_column('breedings', 'manual_sire_color')
    op.drop_column('breedings', 'manual_sire_name')
    # ### end Alembic commands ###
